version: '3.8'
services:
  db:
    container_name: mysql_db
    image: jucamear/ubu-mysql:latest
    environment:
      - USUARIO=juan
      - PASSWD=1234
    networks: 
      mired:
  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      mired:
networks: 
  mired:
      driver: bridge
    
