version: '3.8'
services:
  db:
    container_name: mysql_db
    image: jucamear/ubu-mysql:latest
    environment:
      - USUARIO=juan
      - PASSWD=1234
      - PROYECTO=comics
    networks: 
      mired:
  adminer:
    container_name: adminer_container
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      mired:
  api:
    container_name: apirest
    image: jucamear/ubu-laravel:latest
    environment:
      - USUARIO=juan
      - PASSWD=1234
      - PROYECTO=comics
      - URL=95.111.227.242
    ports:
      - 8081:80
    networks: 
      mired:
networks: 
  mired:
      driver: bridge
    
